# Generated by Django 4.1.3 on 2023-08-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('is_admin', models.BooleanField()),
                ('profile_picture', models.CharField(max_length=55)),
                ('uid', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=55)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('engineer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiomanagerapi.engineer')),
            ],
        ),
        migrations.CreateModel(
            name='SessionEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiomanagerapi.engineer')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiomanagerapi.session')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('brand', models.CharField(max_length=55)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studiomanagerapi.category')),
            ],
        ),
    ]
