# Generated by Django 4.1.3 on 2023-08-22 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studiomanagerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='engineer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='studiomanagerapi.engineer'),
        ),
    ]
